### PR TITLE
Allow hiding the citation & improve docstring

### PR DESCRIPTION
**Pull request by yakir12**
This adds a keyword argument to hide the citation when loading data. It also improves on the docsrtring to the load function.

### CODE REVIEW

**Comment by briochemc** [comment]
LGTM! Thanks! :)

**Comment by yakir12** [comment]
Glad this helps! 

Any chance you could bump the release so people (i.e. me) updating can benefit? I think there is a way to automate that with GH actions, but I don't remember right now.

**Comment by briochemc** [comment]
Oh sure! (I didn't even remember I registered this!)

**Comment by briochemc** [comment]
Done! Should be available in an hour or so I guess 😃

**Comment by briochemc** [comment]
Should be good to go now! https://github.com/JuliaRegistries/General/pull/67473#event-7300873340

**Pull request merged**
